version: "3.9"

services:
  radhey_api:
    build: .
    container_name: radhey_api
    restart: always
    ports:
      - "3307:3307"
    env_file:
      - .env
    environment:
      - DATABASE_URL=postgresql://${POSTGRES_USER:-radhey_user}:${POSTGRES_PASSWORD:-radhey@!7701^$%}@radhey-postgres:5432/${POSTGRES_DB:-radhey_group_db}?schema=public
    depends_on:
      radhey-postgres:
        condition: service_healthy
    volumes:
      - radhey_uploads:/app/uploads
    networks:
      - radhey-network

  radhey-postgres:
    image: postgres:16
    container_name: radhey-postgres
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-radhey_group_db}
      POSTGRES_USER: ${POSTGRES_USER:-radhey_user}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-radhey@!7701^$%}
    ports:
      - "5437:5432"
    volumes:
      - radhey_pg_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks: 
      - radhey-network

volumes:
  radhey_pg_data:
  radhey_uploads:

networks:
  radhey-network: