version: "3.9"

services:
  northwind_api:
    build: .
    container_name: northwind_api
    restart: always
    ports:
      - "4004:4004"
    env_file:
      - .env
    environment:
      - DATABASE_URL=postgresql://${POSTGRES_USER:-northwind_user}:${POSTGRES_PASSWORD:-northwind@!7701^$%}@northwind-postgres:5432/${POSTGRES_DB:-northwind_db}?schema=public
    depends_on:
      northwind-postgres:
        condition: service_healthy
    volumes:
      - northwind_uploads:/app/uploads
    networks:
      - northwind-network

  northwind-postgres:
    image: postgres:16
    container_name: northwind-postgres
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-northwind_db}
      POSTGRES_USER: ${POSTGRES_USER:-northwind_user}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-northwind@!7701^$%}
    ports:
      - "5434:5432"
    volumes:
      - northwind_pg_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB" ]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - northwind-network

volumes:
  northwind_pg_data:
  northwind_uploads:

networks:
  northwind-network:
